import type { DocumentRecord } from './documentTypes'

function dateOffset(days: number): string {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
}

const today = dateOffset(0)
const yesterday = dateOffset(-1)
const twoDaysAgo = dateOffset(-2)
const lastWeek = dateOffset(-7)
const lastMonth = dateOffset(-22)

export const mockDocuments: DocumentRecord[] = [
  {
    id: 'doc-transport-plan-2026',
    name: 'Transport Planning Report 2026.pdf',
    description: 'Annual departmental report',
    referenceNumber: 'FMT/OPS/2026/041',
    type: 'PDF',
    owner: 'You',
    folder: 'Reports',
    modifiedAt: today,
    modifiedLabel: '2 hours ago',
    createdAt: dateOffset(-38),
    size: '4.2 MB',
    starred: true,
    sharedWithMe: false,
    status: 'ready',
    preview: 'This report outlines the department’s transport priorities for 2026, including fleet renewal, route optimization, and service reliability targets. The proposed plan aligns operational spending with the annual service commitments and identifies key actions for each quarter.',
  },
  {
    id: 'doc-q3-department-report',
    name: 'Q3 Department Report.docx',
    description: 'Quarterly activity and outcomes',
    referenceNumber: 'FMT/OPS/2026/038',
    type: 'DOCX',
    owner: 'Sarah Chen',
    folder: 'Reports',
    modifiedAt: today,
    modifiedLabel: '4 hours ago',
    createdAt: dateOffset(-9),
    size: '860 KB',
    starred: false,
    sharedWithMe: true,
    status: 'ready',
    preview: 'The third-quarter review records progress against departmental objectives. Delivery improved across fleet readiness and response times, while procurement lead times remain the primary operational risk. The report recommends a monthly review of open purchasing actions.',
  },
  {
    id: 'doc-staff-circular-october',
    name: 'Staff Circular — October 2026.pdf',
    description: 'Department updates and staff notices',
    referenceNumber: 'FMT/HR/2026/119',
    type: 'PDF',
    owner: 'People Operations',
    folder: 'Memos',
    modifiedAt: today,
    modifiedLabel: 'Yesterday',
    createdAt: yesterday,
    size: '1.1 MB',
    starred: false,
    sharedWithMe: true,
    status: 'ready',
    preview: 'This circular includes October office notices, the updated leave submission schedule, and reminders for the upcoming staff briefing. Team leads should share the revised schedule with their units by Friday.',
  },
  {
    id: 'doc-management-minutes',
    name: 'Meeting Minutes — Management Review.docx',
    description: 'Decisions and follow-up actions',
    referenceNumber: 'FMT/MTG/2026/027',
    type: 'DOCX',
    owner: 'You',
    folder: 'Meetings',
    modifiedAt: yesterday,
    modifiedLabel: 'Yesterday',
    createdAt: dateOffset(-3),
    size: '420 KB',
    starred: true,
    sharedWithMe: false,
    status: 'ready',
    preview: 'The management review covered the Q3 delivery position, vehicle availability, and the 2027 planning calendar. Actions include confirming replacement vehicle costs, circulating the revised service schedule, and returning progress updates before the next review.',
  },
  {
    id: 'doc-procurement-request',
    name: 'Procurement Request.xlsx',
    description: 'Vehicle maintenance supplies request',
    referenceNumber: 'PR-2026-2048',
    type: 'XLSX',
    owner: 'Jordan Lee',
    folder: 'Projects',
    modifiedAt: yesterday,
    modifiedLabel: 'Yesterday',
    createdAt: dateOffset(-5),
    size: '212 KB',
    starred: false,
    sharedWithMe: true,
    status: 'ready',
    preview: 'The request covers scheduled maintenance supplies for the fourth quarter. The estimated total is within the approved maintenance allocation, subject to final review of supplier delivery dates and the revised quotation.',
  },
  {
    id: 'doc-project-progress',
    name: 'Project Progress Report.pptx',
    description: 'Fleet modernization delivery update',
    referenceNumber: 'FMT/PMO/2026/016',
    type: 'PPTX',
    owner: 'You',
    folder: 'Projects',
    modifiedAt: twoDaysAgo,
    modifiedLabel: '2 days ago',
    createdAt: dateOffset(-12),
    size: '6.8 MB',
    starred: false,
    sharedWithMe: false,
    status: 'ready',
    preview: 'The fleet modernization program remains on schedule for the first delivery milestone. Two procurement dependencies require attention: confirmation of the maintenance package and sign-off of the revised delivery sequence.',
  },
  {
    id: 'doc-official-correspondence',
    name: 'Official Correspondence — Ref. No. FMT/ADM/2026/084.pdf',
    description: 'Request for interdepartmental review',
    referenceNumber: 'FMT/ADM/2026/084',
    type: 'PDF',
    owner: 'Administration',
    folder: 'Correspondence',
    modifiedAt: twoDaysAgo,
    modifiedLabel: '2 days ago',
    createdAt: dateOffset(-4),
    size: '980 KB',
    starred: false,
    sharedWithMe: true,
    status: 'ready',
    preview: 'The correspondence requests a consolidated departmental response on the proposed service timetable. Feedback should be returned to Administration by 9 October 2026, with any operational impacts clearly noted.',
  },
  {
    id: 'doc-policy-review',
    name: 'Policy Review Document.docx',
    description: 'Travel and expense policy review',
    referenceNumber: 'POL/FIN/2026/012',
    type: 'DOCX',
    owner: 'You',
    folder: 'Policies',
    modifiedAt: lastWeek,
    modifiedLabel: 'Last week',
    createdAt: dateOffset(-18),
    size: '540 KB',
    starred: true,
    sharedWithMe: false,
    status: 'ready',
    preview: 'The review proposes clearer approval thresholds for local travel and updated receipt requirements. The policy owner should confirm the suggested implementation date and circulate the final guidance to department leads.',
  },
  {
    id: 'doc-budget-summary',
    name: 'Operations Budget Summary.xlsx',
    description: 'Year-to-date spend and forecast',
    referenceNumber: 'FMT/FIN/2026/055',
    type: 'XLSX',
    owner: 'Finance',
    folder: 'Reports',
    modifiedAt: lastWeek,
    modifiedLabel: 'Last week',
    createdAt: dateOffset(-25),
    size: '730 KB',
    starred: false,
    sharedWithMe: true,
    status: 'ready',
    preview: 'Year-to-date operating spend remains within the approved envelope. Fuel and maintenance costs are forecast to finish slightly above plan, offset by lower-than-expected travel expenditure.',
  },
  {
    id: 'doc-meeting-agenda-template',
    name: 'Management Meeting Agenda Template.docx',
    description: 'Reusable agenda for leadership meetings',
    referenceNumber: 'FMT/MTG/TPL/003',
    type: 'DOCX',
    owner: 'You',
    folder: 'Templates',
    modifiedAt: lastWeek,
    modifiedLabel: 'Last week',
    createdAt: dateOffset(-60),
    size: '96 KB',
    starred: false,
    sharedWithMe: false,
    status: 'ready',
    preview: 'A reusable agenda template with sections for decisions, operational updates, outstanding actions, and new business. Meeting owners should circulate the final agenda one working day before each review.',
  },
  {
    id: 'doc-scanned-invoice',
    name: 'Scanned Supplier Invoice.pdf',
    description: 'Invoice scan awaiting text recognition',
    referenceNumber: 'INV-2026-0917',
    type: 'PDF',
    owner: 'You',
    folder: 'Other',
    modifiedAt: today,
    modifiedLabel: 'Just now',
    createdAt: today,
    size: '2.6 MB',
    starred: false,
    sharedWithMe: false,
    status: 'failed',
    preview: 'Text recognition could not complete for this scan. Try processing the document again or upload a clearer copy.',
  },
  {
    id: 'doc-site-inspection-photo',
    name: 'Depot Inspection Photo.jpg',
    description: 'Inspection image from the central depot',
    referenceNumber: 'FMT/OPS/IMG/061',
    type: 'JPG',
    owner: 'Jordan Lee',
    folder: 'Other',
    modifiedAt: lastMonth,
    modifiedLabel: '3 weeks ago',
    createdAt: lastMonth,
    size: '3.4 MB',
    starred: false,
    sharedWithMe: true,
    status: 'processing',
    preview: 'This image is being processed for searchable text and document details.',
  },
]

export async function loadMockDocuments(): Promise<DocumentRecord[]> {
  return mockDocuments.map((document) => ({ ...document }))
}