import type { WriterIconName } from './components/WriterIcon'
import type { DraftDocument, WritingTemplate, WritingType } from './writerTypes'

export const writingTypes: Array<{ id: WritingType; title: string; description: string; icon: WriterIconName }> = [
  { id: 'memo', title: 'Memo', description: 'Internal communication and instructions', icon: 'file' },
  { id: 'letter', title: 'Letter', description: 'Formal external or internal correspondence', icon: 'mail' },
  { id: 'report', title: 'Report', description: 'Structured reports, summaries and updates', icon: 'report' },
  { id: 'email', title: 'Email', description: 'Professional workplace emails', icon: 'send' },
  { id: 'notice', title: 'Notice', description: 'Announcements and official notices', icon: 'notice' },
  { id: 'brief', title: 'Brief', description: 'Concise summaries for decision-makers', icon: 'brief' },
  { id: 'proposal', title: 'Proposal', description: 'Structured proposals and recommendations', icon: 'proposal' },
  { id: 'minutes', title: 'Meeting Minutes', description: 'Record discussions, decisions and actions', icon: 'meeting' },
  { id: 'general', title: 'General Document', description: 'Start with a blank professional document', icon: 'file' },
]

export const templateCategories = ['Official', 'Administrative', 'Reports', 'Communication', 'Meetings'] as const

export const writingTemplates: WritingTemplate[] = [
  { id: 'official-memo', title: 'Official Memo', type: 'memo', category: 'Official', description: 'Internal direction or department update', prompt: 'Write a formal memo to department staff about the current update.', outline: ['Purpose', 'Background', 'Required action', 'Effective date'] },
  { id: 'formal-letter', title: 'Formal Letter', type: 'letter', category: 'Official', description: 'Professional letter to an organization', prompt: 'Draft a formal letter acknowledging the request and outlining the next steps.', outline: ['Reference', 'Opening', 'Response', 'Closing'] },
  { id: 'request-letter', title: 'Request Letter', type: 'letter', category: 'Administrative', description: 'Request information, support or approval', prompt: 'Write a formal request letter with clear context and a response deadline.', outline: ['Purpose of request', 'Background', 'Information required', 'Requested date'] },
  { id: 'response-letter', title: 'Response Letter', type: 'letter', category: 'Communication', description: 'Acknowledge and respond to correspondence', prompt: 'Draft a formal response to the selected correspondence.', outline: ['Acknowledgement', 'Response', 'Next steps', 'Closing'] },
  { id: 'department-report', title: 'Departmental Report', type: 'report', category: 'Reports', description: 'Quarterly activities, outcomes and open actions', prompt: 'Prepare a concise departmental report for the current reporting period.', outline: ['Executive summary', 'Activities', 'Challenges', 'Next steps'] },
  { id: 'project-brief', title: 'Project Brief', type: 'brief', category: 'Reports', description: 'Decision-ready project overview', prompt: 'Create a decision-ready brief describing the project status and recommendations.', outline: ['Purpose', 'Current situation', 'Options', 'Recommendation'] },
  { id: 'staff-notice', title: 'Staff Notice', type: 'notice', category: 'Administrative', description: 'Clear announcement for all department staff', prompt: 'Write a clear notice explaining a process change to staff.', outline: ['Announcement', 'Effective date', 'Required action', 'Contact'] },
  { id: 'meeting-minutes-template', title: 'Meeting Minutes', type: 'minutes', category: 'Meetings', description: 'Capture discussion, decisions and owners', prompt: 'Prepare structured meeting minutes from the notes and agenda.', outline: ['Attendees', 'Agenda', 'Discussion', 'Decisions', 'Actions'] },
  { id: 'follow-up-email', title: 'Follow-up Email', type: 'email', category: 'Communication', description: 'Professional follow-up after a discussion', prompt: 'Write a professional follow-up email confirming decisions and next steps.', outline: ['Greeting', 'Summary', 'Next steps', 'Closing'] },
]

export const recentDrafts: DraftDocument[] = [
  { id: 'draft-q3-report', title: 'Q3 Department Report', type: 'report', content: '', status: 'saved', updatedAt: 'Modified 1 hour ago' },
  { id: 'draft-transport-response', title: 'Response to Planning Department', type: 'letter', content: '', status: 'saved', updatedAt: 'Modified yesterday' },
  { id: 'draft-staff-circular', title: 'Staff Circular', type: 'notice', content: '', status: 'saved', updatedAt: 'Modified Sep 29' },
]

export function typeTitle(type: WritingType): string {
  return writingTypes.find((item) => item.id === type)?.title ?? 'General Document'
}

export function createMockDraft(type: WritingType, brief: string, audience: string, dateLabel: string): { title: string; content: string } {
  const subject = brief.trim().replace(/[.?!]+$/, '') || 'Department Update'
  const titleCase = subject.charAt(0).toUpperCase() + subject.slice(1)
  if (type === 'memo') return { title: titleCase.slice(0, 58), content: `MEMORANDUM\n\nTo: ${audience === 'management' ? 'Department Leadership' : audience === 'official' ? 'All Department Staff' : 'All Department Staff'}\nFrom: Transport Planning & Coordination\nDate: ${dateLabel}\nSubject: ${titleCase}\n\nPurpose\nThis memorandum provides an update regarding ${subject.toLowerCase()}. It outlines the relevant process, expected responsibilities, and actions required from the department.\n\nProcedure\nEffective October 5, 2026, all departmental documents should be submitted through the designated document management process. Include the appropriate reference number and supporting material with each submission.\n\nRequired action\nPlease ensure that submissions are complete and reviewed by the relevant unit lead before they are forwarded for processing.\n\nThank you for your cooperation.\n\nTransport Planning & Coordination` }
  if (type === 'letter') return { title: titleCase.slice(0, 58), content: `Transport Planning & Coordination\nOctober 1, 2026\n\nDear Colleagues,\n\nSubject: ${titleCase}\n\nWe acknowledge receipt of your communication and appreciate the information provided. Our team has reviewed the matter with the relevant unit and is coordinating the next steps.\n\nWe will provide a further update by October 3, 2026. Please include the relevant reference number in any follow-up correspondence.\n\nYours sincerely,\n\nTransport Planning & Coordination` }
  if (type === 'email') return { title: titleCase.slice(0, 58), content: `Subject: ${titleCase}\n\nDear Colleagues,\n\nI am writing to provide an update regarding ${subject.toLowerCase()}. The relevant team is reviewing the available information and confirming the next steps.\n\nPlease share any additional details by October 3, 2026 so they can be included in the consolidated update.\n\nKind regards,\nTransport Planning & Coordination` }
  if (type === 'notice') return { title: titleCase.slice(0, 58), content: `DEPARTMENT NOTICE\n\nTo: ${audience === 'management' ? 'Department Leadership' : 'All Department Staff'}\nDate: ${dateLabel}\n\nSubject: ${titleCase}\n\nThis notice is to inform staff of an update to the departmental process. Effective October 5, 2026, all official submissions should include the appropriate reference number and supporting documents.\n\nAction required\nPlease review the updated procedure and direct questions to Transport Planning & Coordination.\n\nThank you for your attention.` }
  if (type === 'minutes') return { title: titleCase.slice(0, 58), content: `MEETING MINUTES\n\nMeeting: Department Coordination Meeting\nDate: ${dateLabel}\nLocation: Conference Room 2\nAttendees: Transport Planning & Coordination\n\nAgenda\n1. Review previous action items\n2. Department updates\n3. Pending correspondence\n4. Upcoming deadlines\n\nDiscussion\nThe team reviewed current reporting requirements and outstanding correspondence. Department representatives provided updates on active work and upcoming deadlines.\n\nDecisions\n• Updated statistics will be submitted before the next review.\n• Outstanding correspondence will be reviewed this week.\n\nAction items\n• Confirm the report owner and due date.\n• Share the approved template with the department.` }
  if (type === 'report') return { title: titleCase.slice(0, 58), content: `DEPARTMENT REPORT\n\nReporting period: Third Quarter 2026\nPrepared by: Transport Planning & Coordination\nDate: ${dateLabel}\n\nExecutive summary\nThis report provides an overview of departmental activities, outcomes, operational challenges, and planned actions for the next reporting period.\n\nActivities and outcomes\nThe department advanced three major projects during the quarter. Routine coordination improved across planning and operations, and teams continued work on fleet utilization and service reliability.\n\nChallenges\nTwo reports remain outstanding. Procurement lead times and incomplete supporting documentation require follow-up.\n\nNext steps\nConfirm action owners, submit remaining statistics by October 3, 2026, and review progress at the next departmental meeting.` }
  if (type === 'brief') return { title: titleCase.slice(0, 58), content: `DECISION BRIEF\n\nSubject: ${titleCase}\nDate: ${dateLabel}\n\nPurpose\nTo provide decision-makers with a concise overview and recommended next steps.\n\nCurrent situation\nThe department is reviewing Q3 transport activity and coordinating outstanding reporting and follow-up work.\n\nConsiderations\n• Updated vehicle utilization data is required.\n• Two reports remain outstanding.\n• The next submission deadline is October 3, 2026.\n\nRecommendation\nConfirm a responsible owner for each open item and submit the consolidated update before the deadline.` }
  if (type === 'proposal') return { title: titleCase.slice(0, 58), content: `PROPOSAL\n\nSubject: ${titleCase}\nPrepared by: Transport Planning & Coordination\nDate: ${dateLabel}\n\nPurpose\nThis proposal sets out a practical approach to address ${subject.toLowerCase()}.\n\nBackground\nCurrent reporting and coordination processes rely on complete references, clear ownership, and timely follow-up across departments.\n\nProposed approach\n1. Confirm the responsible unit and review timeline.\n2. Use the approved document template and reference format.\n3. Track open actions through the department workflow.\n\nRecommendation\nApprove the proposed approach and review results at the next coordination meeting.` }
  return { title: titleCase.slice(0, 58), content: `${typeTitle(type).toUpperCase()}\n\nTitle: ${titleCase}\nDate: ${dateLabel}\nPrepared by: Transport Planning & Coordination\n\nPurpose\nThis document addresses ${subject.toLowerCase()} and provides a clear record for the intended audience.\n\nDetails\nThe relevant team is reviewing the available information and confirming responsibilities, supporting documents, and the appropriate next steps.\n\nNext steps\nPlease review the information, confirm the responsible owner, and provide any required follow-up by October 3, 2026.` }
}