import type { KnowledgeSource } from '../../../pages/knowledge/knowledgeTypes'
import KnowledgeIcon from '../KnowledgeIcon'
import KnowledgeSourceCard from '../KnowledgeSourceCard/KnowledgeSourceCard'
import './KnowledgeSourceTable.css'

type Props = { sources: KnowledgeSource[]; loading: boolean; onOpen: (source: KnowledgeSource) => void; onAsk: (source: KnowledgeSource) => void; onRefresh: (source: KnowledgeSource) => void; onDetails: (source: KnowledgeSource) => void; onArchive: (source: KnowledgeSource) => void }

export default function KnowledgeSourceTable({ sources, loading, onOpen, onAsk, onRefresh, onDetails, onArchive }: Props) {
  if (loading) return <div className="knowledge-source-skeletons" aria-label="Loading knowledge sources">{Array.from({ length: 4 }, (_, index) => <i key={index} />)}</div>
  return <div className="knowledge-source-table-wrap"><table className="knowledge-source-table"><thead><tr><th>Source</th><th>Type</th><th>Department</th><th>Owner</th><th>Last updated</th><th>Status</th><th>Actions</th></tr></thead><tbody>{sources.map((source) => <tr key={source.id}><td data-label="Source"><button type="button" className="knowledge-source-name" onClick={() => onDetails(source)}><KnowledgeIcon name="file" size={17} /><span>{source.title}</span></button></td><td data-label="Type">{source.type}</td><td data-label="Department">{source.department}</td><td data-label="Owner">{source.owner}</td><td data-label="Last updated">{source.updatedAt}</td><td data-label="Status"><span className={`knowledge-status status-${source.status.toLowerCase().replace(/\s+/g, '-')}`}>{source.status}</span></td><td data-label="Actions"><div className="knowledge-table-actions"><button type="button" onClick={() => onOpen(source)} title="Open document" aria-label={`Open ${source.title}`}><KnowledgeIcon name="external" size={14} /></button><button type="button" onClick={() => onAsk(source)} title="Ask AI" aria-label={`Ask about ${source.title}`}><KnowledgeIcon name="sparkles" size={14} /></button><button type="button" onClick={() => onRefresh(source)} title="Refresh knowledge" aria-label={`Refresh ${source.title}`}><KnowledgeIcon name="refresh" size={14} /></button><button type="button" onClick={() => onDetails(source)} title="View details" aria-label={`Details for ${source.title}`}><KnowledgeIcon name="info" size={14} /></button><button type="button" onClick={() => onArchive(source)} title="Archive source" aria-label={`Archive ${source.title}`}><KnowledgeIcon name="more" size={14} /></button></div></td></tr>)}</tbody></table><div className="knowledge-source-cards">{sources.map((source) => <KnowledgeSourceCard key={source.id} source={source} onOpen={() => onOpen(source)} onAsk={() => onAsk(source)} onRefresh={() => onRefresh(source)} onDetails={() => onDetails(source)} onArchive={() => onArchive(source)} />)}</div></div>
}