import SettingsSection from '../SettingsSection/SettingsSection'
import SettingsSaveState from '../SettingsSaveState/SettingsSaveState'
import SettingsIcon from '../SettingsIcon'
import type { SettingsPanelProps } from '../../../pages/settings/settingsTypes'
import './ProfileSettings.css'

export default function ProfileSettings({ value, onChange, onSave, onCancel, status }: SettingsPanelProps<'profile'>) {
  function update(field: keyof typeof value, next: string) { onChange({ ...value, [field]: next }) }
  return <SettingsSection eyebrow="PERSONAL SETTINGS" title="Profile" description="Update the personal details used across your OfficePilot workspace."><div className="profile-photo-row"><div className="profile-photo-preview">{value.photo ? <img src={value.photo} alt="Profile preview" /> : value.fullName.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><div><strong>Profile photo</strong><p>Use a clear image so teammates can recognize you.</p><label className="settings-upload-button"><SettingsIcon name="upload" size={15} /> Upload photo<input type="file" accept="image/*" onChange={(event) => { const file = event.target.files?.[0]; if (file) update('photo', URL.createObjectURL(file)) }} /></label></div></div><div className="settings-form-grid"><label className="settings-field"><span>Full name</span><input value={value.fullName} onChange={(event) => update('fullName', event.target.value)} /></label><label className="settings-field"><span>Email</span><input type="email" value={value.email} onChange={(event) => update('email', event.target.value)} /></label><label className="settings-field"><span>Phone</span><input type="tel" value={value.phone} onChange={(event) => update('phone', event.target.value)} /></label><label className="settings-field"><span>Job title</span><input value={value.jobTitle} onChange={(event) => update('jobTitle', event.target.value)} /></label><label className="settings-field settings-field-wide"><span>Department</span><input value={value.department} onChange={(event) => update('department', event.target.value)} /></label></div><div className="settings-form-footer"><SettingsSaveState status={status} /><div className="settings-form-actions"><button type="button" className="settings-button-secondary" onClick={onCancel}>Cancel</button><button type="button" className="settings-button-primary" onClick={onSave} disabled={status === 'saving'}>Save changes</button></div></div></SettingsSection>
}