import type { CorrespondenceItem } from './correspondenceTypes'

function dateOffset(days: number): string {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
}

const today = dateOffset(0)
const yesterday = dateOffset(-1)
const twoDaysAgo = dateOffset(-2)
const threeDaysAgo = dateOffset(-3)
const lastWeek = dateOffset(-7)
const lastDay = dateOffset(-1)
const tomorrow = dateOffset(2)
const nextWeek = dateOffset(6)

export const mockCorrespondence: CorrespondenceItem[] = [
  {
    id: 'corr-transport-statistics',
    subject: 'Request for Updated Transport Statistics',
    preview: 'Planning Department is requesting the latest third-quarter transport statistics and vehicle utilization data.',
    message: 'Kindly provide the updated transport statistics for the third quarter, including vehicle utilization data and a brief explanation of any significant variances. Please return the information by October 3, 2026, so it can be included in the consolidated planning report.',
    type: 'incoming',
    referenceNumber: 'FMT/TPC/2026/184',
    sender: 'Planning Department',
    recipient: 'Transport Planning & Coordination',
    department: 'Planning',
    status: 'awaiting-response',
    priority: 'high',
    date: yesterday,
    dateLabel: 'Sep 30, 2026',
    responseDeadline: tomorrow,
    relatedDocuments: [
      { id: 'transport-request-doc', name: 'Q3 Transport Statistics Request.pdf', type: 'PDF', size: '1.2 MB' },
      { id: 'transport-source-report', name: 'Department Activity Report.docx', type: 'DOCX', size: '840 KB' },
    ],
    attachments: [{ id: 'transport-attachment', name: 'Q3 Transport Statistics Request.pdf', type: 'PDF', size: '1.2 MB' }],
    relatedTask: 'Provide Q3 transport statistics',
    notes: 'Include the latest fleet utilization figures from Operations.',
    responseDraft: '',
    activity: [
      { id: 'transport-activity-1', dateLabel: 'Sep 30, 2026', time: '10:42 AM', description: 'Received from Planning Department' },
      { id: 'transport-activity-2', dateLabel: 'Sep 30, 2026', time: '11:15 AM', description: 'Assigned to Transport Planning & Coordination' },
      { id: 'transport-activity-3', dateLabel: 'Sep 30, 2026', time: '12:03 PM', description: 'Opened by you' },
    ],
  },
  {
    id: 'corr-stakeholder-invitation',
    subject: 'Invitation to Stakeholder Coordination Meeting',
    preview: 'The Secretariat invites department representatives to a coordination meeting on service delivery priorities.',
    message: 'You are invited to the Stakeholder Coordination Meeting on October 8, 2026. The meeting will review service delivery priorities and agree on the next quarter’s coordination schedule.',
    type: 'incoming',
    referenceNumber: 'SEC/MEET/2026/092',
    sender: 'Office of the Secretariat',
    recipient: 'Transport Planning & Coordination',
    department: 'Administration',
    status: 'received',
    priority: 'normal',
    date: yesterday,
    dateLabel: 'Sep 30, 2026',
    responseDeadline: nextWeek,
    relatedDocuments: [{ id: 'meeting-agenda', name: 'Stakeholder Meeting Agenda.pdf', type: 'PDF', size: '612 KB' }],
    attachments: [{ id: 'meeting-agenda-attachment', name: 'Stakeholder Meeting Agenda.pdf', type: 'PDF', size: '612 KB' }],
    notes: '',
    responseDraft: '',
    activity: [{ id: 'meeting-invite-activity', dateLabel: 'Sep 30, 2026', time: '2:18 PM', description: 'Received from Office of the Secretariat' }],
  },
  {
    id: 'corr-quarterly-report-request',
    subject: 'Request for Quarterly Activity Report',
    preview: 'Please submit your unit’s quarterly activity report with outcomes and open actions.',
    message: 'Please submit the unit’s quarterly activity report, including key outcomes, risks, and actions that remain open. The report will be reviewed during the departmental planning session.',
    type: 'incoming',
    referenceNumber: 'FMT/ADM/2026/178',
    sender: 'Administration Department',
    recipient: 'Transport Planning & Coordination',
    department: 'Administration',
    status: 'under-review',
    priority: 'high',
    date: twoDaysAgo,
    dateLabel: 'Sep 29, 2026',
    responseDeadline: nextWeek,
    relatedDocuments: [{ id: 'quarterly-report-template', name: 'Quarterly Activity Report Template.docx', type: 'DOCX', size: '328 KB' }],
    attachments: [{ id: 'quarterly-template-attachment', name: 'Quarterly Activity Report Template.docx', type: 'DOCX', size: '328 KB' }],
    relatedTask: 'Compile Q3 unit activity report',
    notes: 'Use the revised template shared by Administration.',
    responseDraft: '',
    activity: [
      { id: 'quarterly-activity-1', dateLabel: 'Sep 29, 2026', time: '9:05 AM', description: 'Received from Administration Department' },
      { id: 'quarterly-activity-2', dateLabel: 'Sep 29, 2026', time: '10:10 AM', description: 'Opened by you' },
    ],
  },
  {
    id: 'corr-pending-document-reminder',
    subject: 'Reminder: Pending Documentation',
    preview: 'A reminder that the supporting documents for the depot maintenance request are still outstanding.',
    message: 'This is a reminder that the supporting documentation for the depot maintenance request has not yet been received. Kindly provide the supplier quotation and inspection note as soon as possible.',
    type: 'incoming',
    referenceNumber: 'FIN/PROC/2026/161',
    sender: 'Procurement Unit',
    recipient: 'Transport Planning & Coordination',
    department: 'Procurement',
    status: 'overdue',
    priority: 'urgent',
    date: lastWeek,
    dateLabel: 'Sep 24, 2026',
    responseDeadline: lastDay,
    relatedDocuments: [{ id: 'maintenance-request', name: 'Depot Maintenance Request.pdf', type: 'PDF', size: '940 KB' }],
    attachments: [{ id: 'maintenance-reminder', name: 'Pending Documents Reminder.pdf', type: 'PDF', size: '304 KB' }],
    relatedTask: 'Send depot maintenance documents',
    notes: 'Supplier quotation is still needed from Fleet Operations.',
    responseDraft: '',
    activity: [{ id: 'reminder-activity', dateLabel: 'Sep 24, 2026', time: '8:30 AM', description: 'Received from Procurement Unit' }],
  },
  {
    id: 'corr-project-update',
    subject: 'Request for Project Status Update',
    preview: 'The Project Management Office needs a concise update on fleet modernization milestones.',
    message: 'Please provide a concise status update on the fleet modernization milestones, including any dependencies that may affect the planned delivery sequence.',
    type: 'incoming',
    referenceNumber: 'PMO/UPD/2026/057',
    sender: 'Project Management Office',
    recipient: 'Transport Planning & Coordination',
    department: 'Projects',
    status: 'received',
    priority: 'normal',
    date: threeDaysAgo,
    dateLabel: 'Sep 28, 2026',
    responseDeadline: nextWeek,
    relatedDocuments: [{ id: 'fleet-status-doc', name: 'Fleet Modernization Status.xlsx', type: 'XLSX', size: '510 KB' }],
    attachments: [],
    notes: '',
    responseDraft: '',
    activity: [{ id: 'project-update-activity', dateLabel: 'Sep 28, 2026', time: '3:34 PM', description: 'Received from Project Management Office' }],
  },
  {
    id: 'corr-circular-response',
    subject: 'Response to Administrative Circular',
    preview: 'Department comments on the revised records retention and filing guidance.',
    message: 'Please find the department’s comments on the revised records retention and filing guidance. The proposed schedule is suitable, subject to the clarifications listed in the attached note.',
    type: 'outgoing',
    referenceNumber: 'FMT/ADM/2026/179',
    sender: 'Transport Planning & Coordination',
    recipient: 'Administration Department',
    department: 'Administration',
    status: 'sent',
    priority: 'normal',
    date: yesterday,
    dateLabel: 'Sep 30, 2026',
    relatedDocuments: [{ id: 'circular-response-note', name: 'Records Guidance Comments.docx', type: 'DOCX', size: '276 KB' }],
    attachments: [{ id: 'circular-response-attachment', name: 'Records Guidance Comments.docx', type: 'DOCX', size: '276 KB' }],
    notes: '',
    responseDraft: '',
    activity: [{ id: 'circular-outgoing-activity', dateLabel: 'Sep 30, 2026', time: '4:12 PM', description: 'Sent to Administration Department' }],
  },
  {
    id: 'corr-vehicle-inquiry-response',
    subject: 'Response to Vehicle Registration Inquiry',
    preview: 'Confirmation of registration records and the next steps for the vehicle transfer.',
    message: 'We confirm that the vehicle registration records have been reviewed. The transfer request is complete, and the updated register is attached for your reference.',
    type: 'outgoing',
    referenceNumber: 'FMT/TPC/2026/179',
    sender: 'Transport Planning & Coordination',
    recipient: 'Operations Department',
    department: 'Operations',
    status: 'sent',
    priority: 'low',
    date: twoDaysAgo,
    dateLabel: 'Sep 29, 2026',
    relatedDocuments: [{ id: 'vehicle-register', name: 'Updated Vehicle Register.xlsx', type: 'XLSX', size: '428 KB' }],
    attachments: [{ id: 'vehicle-register-attachment', name: 'Updated Vehicle Register.xlsx', type: 'XLSX', size: '428 KB' }],
    notes: '',
    responseDraft: '',
    activity: [{ id: 'vehicle-response-activity', dateLabel: 'Sep 29, 2026', time: '1:41 PM', description: 'Sent to Operations Department' }],
  },
  {
    id: 'corr-work-plan-submission',
    subject: 'Submission of Departmental Work Plan',
    preview: 'The department’s approved work plan for the 2026/27 reporting period.',
    message: 'Attached is the approved departmental work plan for the 2026/27 reporting period. The plan includes quarterly delivery milestones and the proposed monitoring schedule.',
    type: 'outgoing',
    referenceNumber: 'FMT/PLN/2026/176',
    sender: 'Transport Planning & Coordination',
    recipient: 'Planning Department',
    department: 'Planning',
    status: 'completed',
    priority: 'high',
    date: threeDaysAgo,
    dateLabel: 'Sep 28, 2026',
    relatedDocuments: [{ id: 'department-plan', name: 'Departmental Work Plan 2026-27.docx', type: 'DOCX', size: '1.4 MB' }],
    attachments: [{ id: 'work-plan-attachment', name: 'Departmental Work Plan 2026-27.docx', type: 'DOCX', size: '1.4 MB' }],
    notes: '',
    responseDraft: '',
    activity: [{ id: 'work-plan-activity', dateLabel: 'Sep 28, 2026', time: '11:06 AM', description: 'Completed by Planning Department' }],
  },
  {
    id: 'corr-workshop-invitation',
    subject: 'Invitation: Regional Operations Workshop',
    preview: 'An invitation to share operational lessons and improvement priorities at the regional workshop.',
    message: 'The department is invited to share operational lessons and improvement priorities at the Regional Operations Workshop on October 14, 2026. Please confirm one representative from your unit.',
    type: 'incoming',
    referenceNumber: 'OPS/EVT/2026/083',
    sender: 'Regional Operations Office',
    recipient: 'Transport Planning & Coordination',
    department: 'Operations',
    status: 'response-drafted',
    priority: 'normal',
    date: today,
    dateLabel: 'Oct 1, 2026',
    responseDeadline: nextWeek,
    relatedDocuments: [{ id: 'workshop-agenda', name: 'Regional Workshop Agenda.pdf', type: 'PDF', size: '768 KB' }],
    attachments: [{ id: 'workshop-invitation-attachment', name: 'Workshop Invitation.pdf', type: 'PDF', size: '512 KB' }],
    notes: '',
    responseDraft: 'Thank you for the invitation. We are pleased to confirm a representative from Transport Planning & Coordination for the workshop.',
    activity: [{ id: 'workshop-activity', dateLabel: 'Oct 1, 2026', time: '9:20 AM', description: 'Response draft created' }],
  },
  {
    id: 'corr-procurement-clarification-draft',
    subject: 'Clarification on Procurement Schedule',
    preview: 'Draft response clarifying the proposed supplier evaluation dates.',
    message: 'Draft response to the procurement schedule request. Confirm the updated evaluation dates with the Procurement Unit before sending.',
    type: 'outgoing',
    referenceNumber: 'FMT/PROC/2026/D-04',
    sender: 'Transport Planning & Coordination',
    recipient: 'Procurement Unit',
    department: 'Procurement',
    status: 'draft',
    priority: 'normal',
    date: today,
    dateLabel: 'Oct 1, 2026',
    relatedDocuments: [],
    attachments: [],
    notes: 'Confirm final dates with Procurement before sending.',
    responseDraft: '',
    activity: [{ id: 'procurement-draft-activity', dateLabel: 'Oct 1, 2026', time: '8:55 AM', description: 'Draft saved by you' }],
  },
  {
    id: 'corr-archived-fuel-allocation',
    subject: 'Fuel Allocation Confirmation',
    preview: 'Confirmation of the revised fuel allocation for the third quarter.',
    message: 'The revised fuel allocation for the third quarter has been confirmed. The approved schedule is attached for reference.',
    type: 'incoming',
    referenceNumber: 'FIN/OPS/2026/142',
    sender: 'Finance Department',
    recipient: 'Transport Planning & Coordination',
    department: 'Finance',
    status: 'archived',
    priority: 'low',
    date: lastWeek,
    dateLabel: 'Sep 24, 2026',
    relatedDocuments: [{ id: 'fuel-allocation-schedule', name: 'Q3 Fuel Allocation Schedule.xlsx', type: 'XLSX', size: '382 KB' }],
    attachments: [{ id: 'fuel-allocation-attachment', name: 'Fuel Allocation Confirmation.pdf', type: 'PDF', size: '560 KB' }],
    notes: '',
    responseDraft: '',
    activity: [{ id: 'fuel-archived-activity', dateLabel: 'Sep 25, 2026', time: '2:48 PM', description: 'Archived by you' }],
  },
]

export async function loadMockCorrespondence(): Promise<CorrespondenceItem[]> {
  return mockCorrespondence.map((item) => ({
    ...item,
    relatedDocuments: item.relatedDocuments.map((file) => ({ ...file })),
    attachments: item.attachments.map((file) => ({ ...file })),
    activity: item.activity.map((activity) => ({ ...activity })),
  }))
}