import { useState } from 'react'
import SettingsSection from '../SettingsSection/SettingsSection'
import SettingsSaveState from '../SettingsSaveState/SettingsSaveState'
import type { SettingsPanelProps } from '../../../pages/settings/settingsTypes'
import './WorkspaceSettings.css'

export default function WorkspaceSettings({ value, onChange, onSave, onCancel, status, isAdmin }: SettingsPanelProps<'workspace'>) {
  const [editing, setEditing] = useState(false)
  function update(field: keyof typeof value, next: string) { onChange({ ...value, [field]: next }) }
  return <SettingsSection eyebrow="WORKSPACE · ADMIN ONLY" title="Workspace" description="Manage the shared defaults and identity used across this OfficePilot workspace."><div className="settings-admin-note">Requires administrator permission. Changes affect everyone in this workspace.</div><div className="settings-form-grid"><label className="settings-field settings-field-wide"><span>Workspace name</span><input value={value.name} onChange={(event) => update('name', event.target.value)} readOnly={!editing || !isAdmin} /></label><label className="settings-field"><span>Workspace ID</span><input value={value.id} readOnly /></label><label className="settings-field"><span>Industry</span><select value={value.industry} onChange={(event) => update('industry', event.target.value)} disabled={!editing || !isAdmin}><option>Public Sector</option><option>Professional Services</option><option>Education</option><option>Healthcare</option></select></label><label className="settings-field"><span>Default department</span><input value={value.department} onChange={(event) => update('department', event.target.value)} readOnly={!editing || !isAdmin} /></label><label className="settings-field"><span>Workspace timezone</span><select value={value.timezone} onChange={(event) => update('timezone', event.target.value)} disabled={!editing || !isAdmin}><option>Africa/Lagos</option><option>Africa/Nairobi</option><option>UTC</option></select></label></div>{isAdmin && <div className="settings-form-footer"><SettingsSaveState status={status} /><div className="settings-form-actions">{editing ? <><button type="button" className="settings-button-secondary" onClick={() => { onCancel(); setEditing(false) }}>Cancel</button><button type="button" className="settings-button-primary" onClick={() => { onSave(); setEditing(false) }} disabled={status === 'saving'}>Save changes</button></> : <button type="button" className="settings-button-secondary" onClick={() => setEditing(true)}>Edit workspace</button>}</div></div>}</SettingsSection>
}