import KnowledgeIcon from '../KnowledgeIcon'
import type { KnowledgeSource } from '../../../pages/knowledge/knowledgeTypes'
import './KnowledgeDetail.css'

type Props = { source: KnowledgeSource; onClose: () => void; onAsk: () => void; onOpen: () => void; onRefresh: () => void; onRemove: () => void; onRelated: (kind: string, title: string) => void }

function RelatedList({ title, items, onSelect }: { title: string; items: string[]; onSelect: (title: string) => void }) { return <div className="knowledge-detail-related-group"><h4>{title}</h4>{items.length ? items.map((item) => <button type="button" key={item} onClick={() => onSelect(item)}><KnowledgeIcon name="file" size={14} />{item}<KnowledgeIcon name="chevron" size={13} /></button>) : <small>None linked</small>}</div> }

export default function KnowledgeDetail({ source, onClose, onAsk, onOpen, onRefresh, onRemove, onRelated }: Props) {
  return <div className="knowledge-detail-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><aside className="knowledge-detail-drawer" role="dialog" aria-modal="true" aria-labelledby="knowledge-detail-title"><header><div><span>SOURCE DETAILS</span><h2 id="knowledge-detail-title">Knowledge source</h2></div><button type="button" aria-label="Close source details" onClick={onClose}><KnowledgeIcon name="close" /></button></header><div className="knowledge-detail-body"><div className="knowledge-detail-title"><span><KnowledgeIcon name="file" size={19} /></span><div><h3>{source.title}</h3><span className={`knowledge-status status-${source.status.toLowerCase().replace(/\s+/g, '-')}`}>{source.status}</span></div></div><p className="knowledge-detail-description">{source.description}</p><dl className="knowledge-detail-fields"><div><dt>Collection</dt><dd>{source.collection}</dd></div><div><dt>Department</dt><dd>{source.department}</dd></div><div><dt>Owner</dt><dd>{source.owner}</dd></div><div><dt>Last updated</dt><dd>{source.updatedAt}</dd></div><div><dt>Visibility</dt><dd><KnowledgeIcon name="shield" size={13} /> {source.visibility}</dd></div><div><dt>Source type</dt><dd>{source.type}</dd></div></dl><section className="knowledge-detail-coverage"><h3>Knowledge coverage</h3><div><span><strong>{source.pagesIndexed}</strong><small>Pages indexed</small></span><span><strong>{source.sectionsIndexed}</strong><small>Sections indexed</small></span><span><strong>{source.lastIndexed}</strong><small>Last indexed</small></span></div></section><section className="knowledge-detail-related"><h3>Related work</h3><RelatedList title="Related documents" items={source.relatedDocuments} onSelect={(title) => onRelated('documents', title)} /><RelatedList title="Related policies" items={source.relatedPolicies} onSelect={(title) => onRelated('policies', title)} /><RelatedList title="Related tasks" items={source.relatedTasks} onSelect={(title) => onRelated('tasks', title)} /><RelatedList title="Related correspondence" items={source.relatedCorrespondence} onSelect={(title) => onRelated('correspondence', title)} /></section></div><footer className="knowledge-detail-actions"><button type="button" onClick={onRefresh}><KnowledgeIcon name="refresh" size={15} /> Refresh knowledge</button><button type="button" onClick={onRemove}><KnowledgeIcon name="trash" size={15} /> Remove from Knowledge</button><button type="button" className="knowledge-primary-button" onClick={onAsk}>Ask about this <KnowledgeIcon name="arrow" size={14} /></button><button type="button" className="knowledge-detail-open" onClick={onOpen}>Open document <KnowledgeIcon name="external" size={14} /></button></footer></aside></div>
}