import SettingsSection from '../SettingsSection/SettingsSection'
import SettingsSaveState from '../SettingsSaveState/SettingsSaveState'
import { notificationPreferenceGroups } from '../../../pages/settings/settingsData'
import type { SettingsPanelProps } from '../../../pages/settings/settingsTypes'
import './NotificationSettings.css'

export default function NotificationSettings({ value, onChange, onSave, onCancel, status }: SettingsPanelProps<'notifications'>) {
  function updateChannel(key: string, channel: 'inApp' | 'email', checked: boolean) { onChange({ ...value, channels: { ...value.channels, [key]: { ...value.channels[key], [channel]: checked } } }) }
  return <SettingsSection eyebrow="PERSONAL SETTINGS" title="Notification preferences" description="Choose which workplace activity OfficePilot surfaces in the app and by email."><div className="notification-preferences-table"><div className="notification-preferences-head"><span>Activity</span><span>In-app</span><span>Email</span></div>{notificationPreferenceGroups.map((group) => <div className="notification-preferences-group" key={group.label}><h3>{group.label}</h3>{group.items.map(([key, label]) => <div className="notification-preference-row" key={key}><span>{label}</span><label aria-label={`${label} in-app`}><input type="checkbox" checked={value.channels[key]?.inApp ?? false} onChange={(event) => updateChannel(key, 'inApp', event.target.checked)} /></label><label aria-label={`${label} email`}><input type="checkbox" checked={value.channels[key]?.email ?? false} onChange={(event) => updateChannel(key, 'email', event.target.checked)} /></label></div>)}</div>)}</div><label className="settings-toggle-row"><input type="checkbox" checked={value.importantActionRequired} onChange={(event) => onChange({ ...value, importantActionRequired: event.target.checked })} /><span><strong>Mark important notifications as action required</strong><small>Highlight updates that need a decision or timely response.</small></span><i /></label><div className="settings-form-footer"><SettingsSaveState status={status} /><div className="settings-form-actions"><button type="button" className="settings-button-secondary" onClick={onCancel}>Cancel</button><button type="button" className="settings-button-primary" onClick={onSave} disabled={status === 'saving'}>Save notification settings</button></div></div></SettingsSection>
}