import './ApprovalContent.css'

type Approval = {
  item: string
  type: string
  content: string
  aiAssisted?: boolean
}

type Props = {
  approval: Approval
}

export default function ApprovalContent({ approval }: Props) {
  return (
    <div className="approval-content">
      <div className="approval-content__header">
        <strong>{approval.item}</strong>
        {approval.aiAssisted ? <span className="ai-badge">AI-assisted draft</span> : null}
      </div>

      <div className="approval-content__meta">
        <span>Generated by OfficePilot</span>
        <span>Reviewed by user</span>
        <span>Awaiting approval</span>
      </div>

      <p>{approval.content}</p>
    </div>
  )
}
