import SettingsSection from '../SettingsSection/SettingsSection'
import SettingsSaveState from '../SettingsSaveState/SettingsSaveState'
import SettingsIcon from '../SettingsIcon'
import type { SettingsPanelProps } from '../../../pages/settings/settingsTypes'
import './OrganizationSettings.css'

export default function OrganizationSettings({ value, onChange, onSave, onCancel, status, isAdmin }: SettingsPanelProps<'organization'>) {
  function update(field: keyof typeof value, next: string) { onChange({ ...value, [field]: next }) }
  return <SettingsSection eyebrow="ORGANIZATION · ADMIN ONLY" title="Organization" description="Organization details appear in workspace records and official correspondence.">{!isAdmin && <div className="organization-readonly-banner">Read-only · Requires administrator permission to make changes.</div>}<div className="organization-id-row"><span>Organization ID</span><strong>{value.id}</strong><small>Managed by OfficePilot</small></div><div className="settings-form-grid"><label className="settings-field settings-field-wide"><span>Organization name</span><input value={value.name} onChange={(event) => update('name', event.target.value)} disabled={!isAdmin} /></label><label className="settings-field"><span>Industry</span><select value={value.industry} onChange={(event) => update('industry', event.target.value)} disabled={!isAdmin}><option>Public Sector</option><option>Professional Services</option><option>Education</option><option>Healthcare</option></select></label><label className="settings-field"><span>Contact email</span><input type="email" value={value.contactEmail} onChange={(event) => update('contactEmail', event.target.value)} disabled={!isAdmin} /></label><label className="settings-field settings-field-wide"><span>Address</span><textarea rows={3} value={value.address} onChange={(event) => update('address', event.target.value)} disabled={!isAdmin} /></label><div className="settings-field settings-field-wide"><span>Organization logo</span><label className="organization-logo-upload"><SettingsIcon name="upload" size={15} /> {value.logo ? 'Change organization logo' : 'Upload organization logo'}<input type="file" accept="image/*" disabled={!isAdmin} onChange={(event) => { const file = event.target.files?.[0]; if (file) update('logo', URL.createObjectURL(file)) }} /></label>{value.logo && <img className="organization-logo-preview" src={value.logo} alt="Organization logo preview" />}</div></div>{isAdmin && <div className="settings-form-footer"><SettingsSaveState status={status} /><div className="settings-form-actions"><button type="button" className="settings-button-secondary" onClick={onCancel}>Cancel</button><button type="button" className="settings-button-primary" onClick={onSave} disabled={status === 'saving'}>Save organization</button></div></div>}</SettingsSection>
}