import { useState, type DragEvent, type FormEvent } from 'react'
import KnowledgeIcon from '../KnowledgeIcon'
import './AddKnowledgeSource.css'

export type AddKnowledgeValues = { title: string; type: 'Policy' | 'Procedure' | 'Guideline' | 'Report' | 'Template' | 'Manual'; department: string; collection: string; description: string; tags: string; visibility: 'Department' | 'Organization'; method: 'Upload Document' | 'Select Existing Document' | 'Add Folder' | 'Add Collection' }
type Props = { onClose: () => void; onSubmit: (values: AddKnowledgeValues) => void }
const methods: AddKnowledgeValues['method'][] = ['Upload Document', 'Select Existing Document', 'Add Folder', 'Add Collection']

export default function AddKnowledgeSource({ onClose, onSubmit }: Props) {
  const [method, setMethod] = useState<AddKnowledgeValues['method']>('Upload Document')
  const [fileName, setFileName] = useState('')
  const [values, setValues] = useState<AddKnowledgeValues>({ title: '', type: 'Policy', department: 'Operations', collection: 'Policies', description: '', tags: '', visibility: 'Department', method: 'Upload Document' })
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onSubmit({ ...values, method, title: values.title.trim() || fileName || 'New Knowledge Source' }) }
  function acceptFile(file?: File) { if (!file) return; setFileName(file.name); setValues((current) => ({ ...current, title: file.name.replace(/\.[^.]+$/, '') })) }
  function dropFile(event: DragEvent<HTMLLabelElement>) { event.preventDefault(); acceptFile(event.dataTransfer.files[0]) }
  function update<K extends keyof AddKnowledgeValues>(key: K, value: AddKnowledgeValues[K]) { setValues((current) => ({ ...current, [key]: value })) }
  return <div className="knowledge-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section className="add-knowledge-modal" role="dialog" aria-modal="true" aria-labelledby="add-knowledge-title"><header className="add-knowledge-header"><div><span>TRUSTED ORGANIZATIONAL SOURCES</span><h2 id="add-knowledge-title">Add Knowledge Source</h2></div><button type="button" aria-label="Close add knowledge source" onClick={onClose}><KnowledgeIcon name="close" /></button></header><div className="knowledge-add-methods" role="tablist" aria-label="Source type">{methods.map((option) => <button type="button" key={option} role="tab" aria-selected={method === option} className={method === option ? 'is-selected' : ''} onClick={() => { setMethod(option); update('method', option) }}>{option}</button>)}</div><form onSubmit={submit}>
    {method === 'Upload Document' && <label className="knowledge-dropzone" onDragOver={(event) => event.preventDefault()} onDrop={dropFile}><input type="file" accept=".pdf,.docx,.pptx,.txt,.png,.jpg,.jpeg,.tif,.tiff" onChange={(event) => acceptFile(event.target.files?.[0])} /><span><KnowledgeIcon name="upload" size={22} /></span><strong>{fileName || 'Drag a document here or browse files'}</strong><small>PDF, DOCX, PPTX, TXT, or images</small></label>}
    {method === 'Select Existing Document' && <label className="knowledge-modal-field"><span>Existing document</span><select value={values.title} onChange={(event) => update('title', event.target.value)}><option value="">Choose a document</option><option>Quarterly Transport Report Q3 2026</option><option>Staff Handbook 2026</option><option>Official Correspondence Template</option></select></label>}
    {method === 'Add Folder' && <p className="knowledge-method-note">Create a folder-backed source group. This will be simulated in the frontend preview.</p>}
    {method === 'Add Collection' && <p className="knowledge-method-note">Create a collection for a trusted workplace knowledge area.</p>}
    <div className="knowledge-add-form-grid"><label className="knowledge-modal-field"><span>{method === 'Add Folder' ? 'Folder name' : method === 'Add Collection' ? 'Collection name' : 'Document title'}</span><input required value={values.title} onChange={(event) => update('title', event.target.value)} placeholder="e.g. Staff Leave Policy 2026" /></label><label className="knowledge-modal-field"><span>Document type</span><select value={values.type} onChange={(event) => update('type', event.target.value as AddKnowledgeValues['type'])}><option>Policy</option><option>Procedure</option><option>Guideline</option><option>Report</option><option>Template</option><option>Manual</option></select></label><label className="knowledge-modal-field"><span>Knowledge collection</span><select value={values.collection} onChange={(event) => update('collection', event.target.value)}><option>Policies</option><option>Procedures</option><option>Guidelines</option><option>Reports</option><option>Templates</option><option>HR</option><option>Finance</option><option>Operations</option></select></label><label className="knowledge-modal-field"><span>Department</span><select value={values.department} onChange={(event) => update('department', event.target.value)}><option>Operations</option><option>HR</option><option>Finance</option><option>Administration</option><option>Transport Planning</option></select></label><label className="knowledge-modal-field knowledge-modal-wide"><span>Description</span><textarea rows={2} value={values.description} onChange={(event) => update('description', event.target.value)} placeholder="What does this source cover?" /></label><label className="knowledge-modal-field knowledge-modal-wide"><span>Tags</span><input value={values.tags} onChange={(event) => update('tags', event.target.value)} placeholder="Separate tags with commas" /></label></div>
    <fieldset className="knowledge-visibility"><legend>Source availability</legend><label><input type="radio" name="knowledge-visibility" checked={values.visibility === 'Department'} onChange={() => update('visibility', 'Department')} /><span><strong>Make available to my department</strong><small>Visible to people with permission in {values.department}.</small></span></label><label><input type="radio" name="knowledge-visibility" checked={values.visibility === 'Organization'} onChange={() => update('visibility', 'Organization')} /><span><strong>Make available organization-wide</strong><small>Organization-wide visibility requires the appropriate administrator permission and source access rights.</small></span></label></fieldset>
    <footer className="knowledge-add-footer"><span>Files and indexing are simulated in this frontend preview.</span><div><button type="button" onClick={onClose}>Cancel</button><button type="submit" className="knowledge-primary-button">Add to Knowledge <KnowledgeIcon name="arrow" size={14} /></button></div></footer>
  </form></section></div>
}